services:
  - type: web
    name: wiki-roaster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false 